baseURL = "https://emanuelpina.pt/"
languageCode = "en-gb"
title = "Emanuel Pina"
metaDataFormat = "yaml"
enableRobotsTXT = true
paginatePath = "page"
enableEmoji = true
enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[params]
  author = "Emanuel Pina"
  description = "Blog de Emanuel Pina"
  thumbnail = "v1568177166/mugshot_xl.jpg"
  readmore = "Read more"
  paginationpath = "page"
  imagecdn = "https://img.emanuelpina.pt/"
  videocdn = "https://iframe.mediadelivery.net/embed/1163/"
  gitsource = "https://codeberg.org/emanuelpina/emanuelpina.pt/src/branch/"
  pgpkeyfingerprint = "52DD0B5CF4F6AB67ADC78D7F2E479ED0E3BA5D22"

[permalinks]
  posts = "/:title/"
  categories = "/categories/:title/"
  tags = "/tags/:title/"

[frontmatter]
  lastmod = ["lastmod", "publishDate", ":git", "date"]