[build]
  command = "hugo --minify"
  publish = "public"
  
[build.environment]
  HUGO_VERSION = "0.84.0"

[[headers]]
  for = "/*"
  [headers.values]
    strict-transport-security = "max-age=31536000; includeSubDomains"
    x-content-type-options = "nosniff"
    x-frame-options = "SAMEORIGIN"
    x-xss-protection = "1; mode=block"
    referrer-policy = "strict-origin-when-cross-origin"
    permissions-policy = "interest-cohort=()"
    content-security-policy = "default-src 'self' *.emanuelpina.pt *.mnlpn.xyz"