[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' *.emanuelpina.pt *.mnlpn.xyz"
        Referrer-Policy = "strict-origin-when-cross-origin"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"
        Permissions-Policy = "interest-cohort=()"

[[redirects]]
    from = "https://emanuelpina.netlify.app/*"
    to = "https://emanuelpina.pt/:splat"
    status = 301
    force = true